# see https://symfony.com/doc/current/reference/configuration/framework.html
framework:
    secret: '%env(APP_SECRET)%'
    #csrf_protection: true
    #http_method_override: true

    # Enables session support. Note that the session will ONLY be started if you read or write from it.
    # Remove or comment this section to explicitly disable session support.
    session:
        handler_id: null
        cookie_secure: auto
        cookie_samesite: lax

    http_client:
        scoped_clients:
            app.open.street.map:
                base_uri: 'https://api.openweathermap.org/'
                headers:
                    'Authorization': 'Bearer e6b30269a76ed8b80cdee26aaabffc74'
                # HTTP Bearer authentication (also called token authentication)
                #auth_bearer: e6b30269a76ed8b80cdee26aaabffc74



    #esi: true
    #fragments: true
    php_errors:
        log: true
